/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [JobPostsKey]
      ,[TTTTTT].[dbo].[DimDate].[Date]
      ,[TTTTTT].[dbo].[DimLocation].[City]
	  ,[TTTTTT].[dbo].[DimLocation].[State]
	  ,[TTTTTT].[dbo].[DimLocation].[Geo]
      ,[TTTTTT].[dbo].[DimJob].[Category]
	  ,[TTTTTT].[dbo].[DimJob].[JobTitle]
      ,[TTTTTT].[dbo].[DimCompany].[CompanyName]
      ,[TTTTTT].[dbo].[DimJobType].[CompanyName] --Need Change
      ,[TTTTTT].[dbo].[DimBoard].[BoardName]
      ,[JobDescription]
      ,[Url]
      ,[Count]
      ,[Salary]
      ,[Hour]
      ,[Minute]
      ,[Second]
  FROM [TTTTTT].[dbo].[FactJobPosts]
	JOIN [TTTTTT].[dbo].[DimBoard]
		ON [TTTTTT].[dbo].[FactJobPosts].[BoardKey] = [TTTTTT].[dbo].[DimBoard].[BoardKey]
	JOIN [TTTTTT].[dbo].[DimCompany]
		ON [TTTTTT].[dbo].[FactJobPosts].[CompanyKey] = [TTTTTT].[dbo].[DimCompany].[CompanyKey]
	JOIN [TTTTTT].[dbo].[DimJobType]
		ON [TTTTTT].[dbo].[FactJobPosts].[JobTypeKey] = [TTTTTT].[dbo].[DimJobType].[JobTypeKey]
	JOIN [TTTTTT].[dbo].[DimDate]
		ON [TTTTTT].[dbo].[FactJobPosts].[DateKey] = [TTTTTT].[dbo].[DimDate].[DateKey]
	JOIN [TTTTTT].[dbo].[DimJob]
		ON [TTTTTT].[dbo].[FactJobPosts].[JobKey] = [TTTTTT].[dbo].[DimJob].[JobKey]
	JOIN [TTTTTT].[dbo].[DimLocation]
		ON [TTTTTT].[dbo].[FactJobPosts].[LocationKey] = [TTTTTT].[dbo].[DimLocation].[LocationKey]